client/components/About.js
client/components/Home.js
client/components/Leaderboard.js
client/components/index.js
client/components/navbar.js
client/routes.js
public/style.css

feat: Webpage front-end react and redux components

---

server/api/locations.js

fix route type

---

server/api/locations.js
server/db/models/Location.js

-added a get and put request for the target

added backend routes to update target

---

package-lock.json
server/api/locations.js

[refactor] cleaned up the code in server/api/locations.js

---

script/seed.js

[FEAT] made 3 killzones in fullstack and reduced radii to 15m

---

server/api/locations.js

fixes a bug preventing locaiton stuff

---

server/api/locations.js

[BUGFIX] put route

---

server/api/locations.js

this adds a debug route to activate locations remotely

---

server/api/locations.js

fixes scoring route

---

server/api/locations.js

-get route grabs all locations that are currently active

added get route to get all active locations

---

server/socket/index.js

[FEAT] Implemented socket on back-end

---

server/api/locations.js
server/socket/index.js

[FEAT] make game redirect to 'you won' or 'you lost' upon target death

---

server/socket/index.js

working up the backend for pvp interaction

---

server/socket/index.js

missing arg for update

---

server/socket/index.js

[BUGFIX] reducer

---

server/socket/index.js

[BUGFIX] fix server's room object

---

server/socket/index.js

[BUGFIX] fixed whether player can see other agents

---

server/socket/index.js

[BUGFIX] reset state of room after a game is over

---

server/socket/index.js

[BUGFIX] added missing argument in updateAgent

---

server/api/locations.js

[BUGFIX] changed mismatched variable names in post route to /active

---

script/seed.js
server/db/models/Location.js

[UPDATE] added name field to location model. updated seed file

---

server/db/models/user.js

[feat]validate email

---

server/api/locations.js

[FEAT] added route to activate all locations

---

server/api/locations.js

[BUGFIX] fixed typo

---

server/api/locations.js

[BUGFIX] fixed another dumb bug

---

server/socket/index.js

[REFACTOR] Smooth agent tracking

---

server/socket/index.js

[FEAT] server side impl for pvp

---

server/api/users.js

[FEAT] Backend for loser score update

---

server/api/users.js

[BUGFIX] fixed score not updating
